language: scala
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2/cache
scala:
  - 2.12.7
  - 2.11.12
jdk:
  - oraclejdk8
script:
  - sbt clean coverage test
after_success:
  - sbt coverageReport codacyCoverage coveralls
